#!/bin/bash

MY_PATH="`dirname \"$0\"`"
cd "$MY_PATH"

./PackageMaker.app/Contents/MacOS/PackageMaker --doc app.pmdoc --out ../Installer/MAC/app.pkg
hdiutil create -srcfolder ../Installer/MAC/app.pkg -ov ../Installer/MAC/app.dmg

exit 0
